version: "3.8"

services:

  controle_bens_frontend:
    depends_on:
      - controle_bens_backend
    networks:
      - controle_bens_network
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  controle_bens_backend:
    depends_on:
      - controle_bens_db
    networks:
      - controle_bens_network
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
      
  controle_bens_db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - controle_bens_network

volumes:
  db_data:
    name: controle_bens_db_data
networks:
  controle_bens_network:
    driver: bridge
